cache: bundler
language: ruby
rvm:
  - 2.4.3
  - 2.5.0
  - 2.6.6
  - ruby-head

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_5.2.gemfile
  exclude:
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.0.gemfile
